CREATE TABLE IF NOT EXISTS winners.legajos
(
    clipro character(2) COLLATE pg_catalog."default" NOT NULL,
    codigo integer NOT NULL,
    apellido character(30) COLLATE pg_catalog."default",
    nombre character(30) COLLATE pg_catalog."default",
    domicilio character(35) COLLATE pg_catalog."default",
    localidad character(25) COLLATE pg_catalog."default",
    nuevocodpostal character(14) COLLATE pg_catalog."default",
    jurisdiccion smallint,
    pais smallint,
    telefono character(30) COLLATE pg_catalog."default",
    fax character(30) COLLATE pg_catalog."default",
    celular character(30) COLLATE pg_catalog."default",
    e_mail character(100) COLLATE pg_catalog."default",
    e_mail2 character(40) COLLATE pg_catalog."default",
    documento smallint,
    cuit character(13) COLLATE pg_catalog."default",
    tipoiva character(3) COLLATE pg_catalog."default",
    tipoingbrutos character(3) COLLATE pg_catalog."default",
    numeroingbrutos character(20) COLLATE pg_catalog."default",
    numerootrimpuestos character(20) COLLATE pg_catalog."default",
    formapago smallint,
    grupo smallint,
    tienesublegajos smallint,
    tienesucursales smallint,
    fechaalta date,
    fechaespecial date,
    fecharelacionada date,
    libroiva character(2) COLLATE pg_catalog."default",
    cuentafact smallint,
    sitimpositiva smallint,
    subcuentas smallint,
    tipolegajoctacte character(2) COLLATE pg_catalog."default",
    cuentactacte smallint,
    tarjeta smallint,
    numerotarjeta character(24) COLLATE pg_catalog."default",
    inactivo smallint,
    integridad smallint,
    tiporetencion character(1) COLLATE pg_catalog."default",
    codigoretencionnacional smallint,
    listaprecios smallint,
    descuento numeric(5,2),
    zona smallint,
    tipovendedor character(2) COLLATE pg_catalog."default",
    vendedor integer,
    entrega character(60) COLLATE pg_catalog."default",
    expreso smallint,
    usaadicionalesfacturas smallint,
    emitirfacturasenotramoneda smallint,
    moneda smallint,
    liquidarcomisiones smallint,
    comisionventa numeric(8,4),
    comisioncobranza numeric(5,2),
    limitectacte numeric(18,2),
    deudactacte numeric(18,2),
    limitevalores numeric(18,2),
    deudavalores numeric(18,2),
    observ_1 character(60) COLLATE pg_catalog."default",
    observ_2 character(60) COLLATE pg_catalog."default",
    observ_3 character(60) COLLATE pg_catalog."default",
    omitirnoalaorden smallint,
    ordencheque character(60) COLLATE pg_catalog."default",
    cbu character(25) COLLATE pg_catalog."default",
    string1 character(20) COLLATE pg_catalog."default",
    string2 character(20) COLLATE pg_catalog."default",
    string3 character(20) COLLATE pg_catalog."default",
    string4 character(20) COLLATE pg_catalog."default",
    long1 integer,
    long2 integer,
    long3 integer,
    long4 integer,
    byte1 smallint,
    byte2 smallint,
    byte3 smallint,
    byte4 smallint,
    decimal1 numeric(12,2),
    decimal2 numeric(12,2),
    decimal3 numeric(12,2),
    decimal4 numeric(12,2),
    depositotransferencia smallint,
    tienedescuentosespeciales smallint,
    convmulti smallint,
    omitircontrolfacturasvencidas smallint,
    legajobloqueadopordeudas smallint,
    fechaexcepcionbloqueo date,
    nombrefantasia character(40) COLLATE pg_catalog."default",
    centrocostos integer,
    porcentregapreventa smallint,
    bloqueoentregapreventa smallint,
    enviofactmail smallint,
    destinatariofactmail character(30) COLLATE pg_catalog."default",
    emailfactmail character(100) COLLATE pg_catalog."default",
    dgrcaba character(2) COLLATE pg_catalog."default",
    legajodeexportacion smallint,
    exportadoalblock date,
    nocalculaibtucuman smallint,
    unidadnegocio smallint,
    generapedidosexportacion smallint,
    latitud character(30) COLLATE pg_catalog."default",
    longitud character(30) COLLATE pg_catalog."default",
    entregalunes smallint,
    entregamartes smallint,
    entregamiercoles smallint,
    entregajueves smallint,
    entregaviernes smallint,
    entregasabado smallint,
    entregadomingo smallint,
    tipobloqueo character(40) COLLATE pg_catalog."default",
    motivobloqueo character(50) COLLATE pg_catalog."default",
    imprimirtextoequivalencia smallint,
    omitircontrolexpblock smallint,
    permitirfactaindum smallint,
    docindum smallint,
    caracterindum character(1) COLLATE pg_catalog."default",
    motivoexcepcionindum character(1) COLLATE pg_catalog."default",
    fechaddjjindum date,
    nrodocindum character(13) COLLATE pg_catalog."default",
    venceddjjindum date,
    proveemonotr character(2) COLLATE pg_catalog."default",
    omitirproductoscompuestos smallint,
    deposenconsigna integer,
    lejanoexpalblock smallint,
    pedidosewinners smallint,
    aplicarretencionespago smallint,
    usafacturacredito smallint,
    tipocomprarg4520 character(1) COLLATE pg_catalog."default",
    sucbcocheque smallint,
    observadoporafip smallint,
    porcretauto numeric(7,2),
    rentabilidad numeric(7,2),
    regsimpdgr smallint,
    fechafinexcepcion date,
    facturanomotro smallint,
    nombrefact character(70) COLLATE pg_catalog."default",
    tipoivafact character(3) COLLATE pg_catalog."default",
    documentofact smallint,
    cuitfact character(13) COLLATE pg_catalog."default",
    domiciliofact character(35) COLLATE pg_catalog."default",
    localidadfact character(25) COLLATE pg_catalog."default",
    jurisdiccionfact smallint,
    paisfact smallint,
    idcompradorml character(20) COLLATE pg_catalog."default",
    diasefectivopago smallint,
    sector character(30) COLLATE pg_catalog."default",
    autorizante smallint,
    pendienterevision smallint,
    esunclub smallint,
    codclub smallint,
    coddivision smallint,
    esagdepcolectivo smallint,
    enviarinfdeudamail smallint,
    tipoenviomail character(1) COLLATE pg_catalog."default",
    nomdestenviomail character(30) COLLATE pg_catalog."default",
    destenviomail character(200) COLLATE pg_catalog."default",
    montocontrolmail numeric(12,2),
    diasvtodeudamail smallint,
    adjuntoocuerpomail character(1) COLLATE pg_catalog."default",
    tipodocdf character(1) COLLATE pg_catalog."default",
    nrodocdf integer,
    codigodf character(38) COLLATE pg_catalog."default",
    calledf character(30) COLLATE pg_catalog."default",
    numerodf character(10) COLLATE pg_catalog."default",
    pisodf character(10) COLLATE pg_catalog."default",
    departamentodf character(10) COLLATE pg_catalog."default",
    clasificaciondf character(30) COLLATE pg_catalog."default",
    tipodf character(30) COLLATE pg_catalog."default",
    categoriadf character(30) COLLATE pg_catalog."default",
    exportadodf smallint,
    fechaexportaciondf date,
    descuentodf character(10) COLLATE pg_catalog."default",
    incluirservicioscomp smallint,
    pagoexento smallint,
    detallarpesopedidos smallint,
    password character(20) COLLATE pg_catalog."default",
    tipopetronas character(3) COLLATE pg_catalog."default",
    cargaobligatoriaficha smallint,
    fichaafa1 character(200) COLLATE pg_catalog."default",
    fichaafa2 character(200) COLLATE pg_catalog."default",
    tipocuenta character(20) COLLATE pg_catalog."default",
    cbuproveedor character(22) COLLATE pg_catalog."default",
    sucursaldf smallint,
    cliprodf character(2) COLLATE pg_catalog."default" DEFAULT 'DF'::bpchar,
    legajodf integer,
    exportadoabelzu date,
    CONSTRAINT key01_legajos PRIMARY KEY (clipro, codigo)
)