CREATE TABLE IF NOT EXISTS winners.liprcabe
(
    codigo smallint NOT NULL,
    nombre character(40) COLLATE pg_catalog."default",
    nombrecorto character(15) COLLATE pg_catalog."default",
    incluyeimpuestos smallint,
    usoindistinto smallint,
    inactivo smallint,
    integridad smallint,
    fecha date,
    vigenciaespecial smallint,
    vigenciadesde date,
    vigenciahasta date,
    usamonedaextranjera smallint,
    moneda smallint,
    calculardesde character(1) COLLATE pg_catalog."default",
    listaoriginal smallint,
    porcentaje numeric(18,4),
    redondearprecios smallint,
    redondearanumero numeric(10,2),
    string1 character(20) COLLATE pg_catalog."default",
    string2 character(20) COLLATE pg_catalog."default",
    short1 smallint,
    short2 smallint,
    byte1 smallint,
    byte2 smallint,
    long1 integer,
    long2 integer,
    controlarcontracosto smallint,
    exportardf smallint,
    listadf character(5) COLLATE pg_catalog."default",
    CONSTRAINT key01_liprcabe PRIMARY KEY (codigo)
)